### ISSUE TITLE
Feature Request: Sorting users based on roles

### ISSUE THREAD

**Issue by gurjyot** [FriendsOfFlarum/user-directory#10]
This will probably solve the need for having a team page as people always want to know who are the ones handling the community. Since all the user sortings are already in this extension so maybe, sorting users based on roles would also fit here.

**Comment by clarkwinkelmann** [comment]
Would this be a filter or sorting based on role ?

We currently don't have any filter on the users page, but that could be nice.

Sorting users based on groups is more difficult, because we need to give a priority to groups somehow, unless we just sort by the number of groups users have (which might not give the expected results at all)

**Comment by splitbrain** [comment]
:1: for a filter

There is currently no way to easily see who is in a group. And I think that's essential when setting up permissions. Having a role filter in the user directory would solve that problem *and* give users a way to see who's in which team.
