### ISSUE TITLE
CSS bug in Google Chrome

### ISSUE THREAD

**Issue by glowingblue** [FriendsOfFlarum/user-directory#33]
There is a CSS bug on Google Chrome, when `.Select select { width: auto }` is disabled it looks OK. This `width : auto` is from the flarum/core CSS code.

![screenshot](https://i.imgur.com/wL7w2y4.png)

**Comment by clarkwinkelmann** [comment]
I can confirm it's broken on Chrome.

Not sure why exactly, probably some CSS witchcraft.

Flarum is using a `Dropdown` instead of a `Select` for the sorting on the discussion list, so I sugges we replace our Select with a Dropdown. It will fix the issue and make it more streamlined with the index page.

**Comment by Ralkage** [comment]
This bug doesn't seem present anymore in Chrome; not sure when or where this was fixed, but you can see which version of Chrome I'm on now and the version of Flarum that this bug is no longer present on:

![image](https://user-images.githubusercontent.com/2059356/113460479-f8bf9b80-93e6-11eb-9bf6-88ce3547e2ed.png)

![image](https://user-images.githubusercontent.com/2059356/113460499-0117d680-93e7-11eb-9886-10ea52743323.png)

If the issue still persists, please let us know by creating a new issue; in hindsight, we're going to go head and closed this issue as fixed.
