### ISSUE TITLE
Display discussion count and post count on user card

### ISSUE THREAD

**Issue by askvortsov1** [FriendsOfFlarum/user-directory#40]
When on the user directory page, we should display metadata such as the discussion count and post count on the user card.

**Comment by clarkwinkelmann** [comment]
That would make sense.

I believe this can already be done. All User Directory does is use the UserCard component. Any extension can extend that component and make changes. It's possible to know when the card is shown under the directory by the className prop.

**Comment by Ralkage** [comment]
I would still like to add this feature some time in the near future!

@askvortsov1 given that we have https://github.com/FriendsOfFlarum/user-directory/issues/57 open, would it make sense to at least have icons represent these counts instead of `Discussions: {count}` and `Posts: {count}`? Not sure which ones would fit for both of these attributes.

**Comment by imorland** [comment]
Added in https://github.com/FriendsOfFlarum/user-directory/pull/92
