### ISSUE TITLE
Extend IndexPage to avoid replicating nav logic

### ISSUE THREAD

**Issue by askvortsov1** [FriendsOfFlarum/user-directory#42]
As long as we override all the search related and view related methods (which we are doing), this might be cleaner?

**Comment by clarkwinkelmann** [comment]
I'm not in favor of this. Breaking changes will hit us even harder.

While not exactly the same we had a related issue recently. We extended the avatar upload controller for the watermark image upload in FoF Upload. A change of the constructor signature between beta 12 and beta 13 broke FoF Upload https://github.com/FriendsOfFlarum/upload/issues/214 We3 would have been better copying the whole code instead of extending the class.

Ideally Flarum should clarify which parts of the javascript/PHP constitutes the public API though. I personally don't think most core components should be listed as extendable outside of modals/alerts and the base component/page.

**Comment by askvortsov1** [comment]
Alright, that definitely makes sense!
