### ISSUE TITLE
Need compatibility with Beta 14

### ISSUE THREAD

**Issue by lostsnow** [FriendsOfFlarum/user-directory#47]
Actually miss compatibility with Beta 14

https://docs.flarum.org/extend/update-b14.html

https://github.com/PeopleInside/Flarum_Beta14_Upgrade/issues/1

**Comment by luceos** [comment]
We are well aware that some extensions aren't up to date yet. Bumping them under our noses like this isn't really civil.

Please have patience for extensions to be slowly patched, provide funding so that we can dedicate paid hours to that through donating at https://opencollective.com/fof or provide a tested Pull Request for the upgrade of this extension.

Thank you for your understanding.
